= LibreOffice Macros

Write and embed LibreOffice Java macros with Maven.

Copyright (C) 2021 J. Férard

License: GPL v3

== Goal
The main goal is to inject libreoffice macros written in java in an ODF file using a Maven plugin.

The example aims to insert CSV data inside a HSQLDB database and then build some queries.

== The maven plugin ==
What it does:
* insert script files in an ODF file without scripts to generate an new ODF file
* update the `META/manifest.xml` file.

What it does not (though it might in a future version):
* generate the parcel-descriptor

== The libre office macros tools ==
It's a simple module, currenty a simple class. To embed this module into an project, use the following command:

[source,bash]
----
mvn clean install && cp libreoffice-macros-tools/target/libreoffice-macros-tools-0.0.1-SNAPSHOT.jar my/porject/src/main/resources/embed/
----

== The example ==
This is a basic example that creates a database, links LiberOffice Base to this database and adds a query.

[source,bash]
----
mvn clean install && cp libreoffice-macros-tools/target/libreoffice-macros-tools-0.0.1-SNAPSHOT.jar libreoffice-macros-example/src/main/resources/embed/ && libreoffice libreoffice-macros-example/target/classes/empty-target.odb
----
